// Package apidocs Code generated by swaggo/swag. DO NOT EDIT
package apidocs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/actors": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actors"
                ],
                "summary": "List known actors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/git_erwanleboucher_dev_eleboucher_apoci_internal_database.Actor"
                            }
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/follows": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "List followers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/git_erwanleboucher_dev_eleboucher_apoci_internal_database.Actor"
                            }
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "Follow a peer",
                "parameters": [
                    {
                        "description": "Target to follow",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.adminFollowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "followed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "missing target",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "could not add follow",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Removes a follow relationship; set force to purge local records even if the peer is unreachable.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "Unfollow a peer",
                "parameters": [
                    {
                        "description": "Target to unfollow",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.adminFollowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "removed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "missing target",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Sets the tag-glob filter controlling which tags are delivered to an inbound follower.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "Set follower tag filter",
                "parameters": [
                    {
                        "description": "Target and tag globs",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.adminFollowFilterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updated, tag_globs",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "missing target or invalid glob",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "follower not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/follows/accept": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "Accept a follow request",
                "parameters": [
                    {
                        "description": "Target to accept",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.adminFollowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "accepted, optional followed_back",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "missing target",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/follows/outgoing": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "List outgoing follows",
                "parameters": [
                    {
                        "enum": [
                            "pending",
                            "accepted",
                            "rejected"
                        ],
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/git_erwanleboucher_dev_eleboucher_apoci_internal_database.Actor"
                            }
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/follows/pending": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "List pending follow requests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/git_erwanleboucher_dev_eleboucher_apoci_internal_database.FollowRequest"
                            }
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/follows/reject": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "Reject a follow request",
                "parameters": [
                    {
                        "description": "Target to reject",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.adminFollowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rejected",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "missing target",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/gc": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gc"
                ],
                "summary": "Garbage collector status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.GCStatusResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Runs a single garbage-collection cycle synchronously.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gc"
                ],
                "summary": "Run garbage collection",
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/identity": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "identity"
                ],
                "summary": "Get node identity",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/git_erwanleboucher_dev_eleboucher_apoci_internal_admin.IdentityResponse"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/images": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "List locally hosted images",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/git_erwanleboucher_dev_eleboucher_apoci_internal_admin.ImageEntry"
                            }
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mirrors/{repo}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Drops a locally-mirrored upstream repository (or a single manifest by digest). Does not affect the upstream.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mirrors"
                ],
                "summary": "Evict a mirrored repository",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repository name",
                        "name": "repo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Evict only this manifest digest (sha256:...)",
                        "name": "digest",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "evicted, blobsPurged",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "invalid request or locally-owned repository",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "repository not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/peers/blocked": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "peers"
                ],
                "summary": "List blocked peers",
                "responses": {
                    "200": {
                        "description": "domains, actors",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/peers/pause": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Blocks inbound federation from a domain or actor without a restart. The block is in-memory and does not survive a config reload.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "peers"
                ],
                "summary": "Pause a peer",
                "parameters": [
                    {
                        "description": "Domain or actor to block",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.adminPeerBlockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "paused",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "missing or invalid domain/actor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/peers/resume": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "peers"
                ],
                "summary": "Resume a peer",
                "parameters": [
                    {
                        "description": "Domain or actor to unblock",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.adminPeerBlockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "resumed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "missing or invalid domain/actor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/replication": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "replication"
                ],
                "summary": "Replication status",
                "responses": {
                    "200": {
                        "description": "enabled, targets",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "git_erwanleboucher_dev_eleboucher_apoci_internal_admin.IdentityResponse": {
            "type": "object",
            "properties": {
                "accountDomain": {
                    "type": "string"
                },
                "actorURL": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "keyID": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "publicKey": {
                    "type": "string"
                }
            }
        },
        "git_erwanleboucher_dev_eleboucher_apoci_internal_admin.ImageEntry": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "git_erwanleboucher_dev_eleboucher_apoci_internal_database.Actor": {
            "type": "object",
            "properties": {
                "actor_url": {
                    "type": "string"
                },
                "alias": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "federation_tag_globs": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_healthy": {
                    "description": "Health \u0026 replication (for blob fetching)",
                    "type": "boolean"
                },
                "last_seen_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "public_key_pem": {
                    "type": "string"
                },
                "replication_policy": {
                    "type": "string"
                },
                "they_follow_us": {
                    "description": "Inbound: they follow us",
                    "type": "boolean"
                },
                "they_follow_us_at": {
                    "type": "string"
                },
                "we_follow_accept_at": {
                    "type": "string"
                },
                "we_follow_status": {
                    "description": "pending, accepted, rejected",
                    "type": "string"
                },
                "we_follow_them": {
                    "description": "Outbound: we follow them",
                    "type": "boolean"
                }
            }
        },
        "git_erwanleboucher_dev_eleboucher_apoci_internal_database.FollowRequest": {
            "type": "object",
            "properties": {
                "actorURL": {
                    "type": "string"
                },
                "alias": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "publicKeyPEM": {
                    "type": "string"
                },
                "requestedAt": {
                    "type": "string"
                }
            }
        },
        "internal_server.GCStatusResponse": {
            "type": "object",
            "properties": {
                "intervalMs": {
                    "type": "integer"
                },
                "lastDurationMs": {
                    "type": "integer"
                },
                "lastRun": {
                    "type": "string"
                },
                "nextRunEstimate": {
                    "type": "string"
                },
                "running": {
                    "type": "boolean"
                }
            }
        },
        "internal_server.adminFollowFilterRequest": {
            "type": "object",
            "properties": {
                "tag_globs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "internal_server.adminFollowRequest": {
            "type": "object",
            "properties": {
                "force": {
                    "type": "boolean"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "internal_server.adminPeerBlockRequest": {
            "type": "object",
            "properties": {
                "actor": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Admin token as \"Bearer \u003ctoken\u003e\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/admin",
	Schemes:          []string{},
	Title:            "apoci admin API",
	Description:      "Administrative API for an apoci federated OCI registry node.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
