apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apoci.fullname" . }}
  labels:
    {{- include "apoci.labels" . | nindent 4 }}
data:
  apoci.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
