{{- if and (not .Values.auth.existingSecret) (or .Values.auth.registryToken .Values.auth.adminToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apoci.fullname" . }}
  labels:
    {{- include "apoci.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.auth.registryToken }}
  registryToken: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.adminToken }}
  adminToken: {{ . | quote }}
  {{- end }}
{{- end }}
