package config

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func writeConfig(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "apoci.yaml")
	require.NoError(t, os.WriteFile(path, []byte(content), 0o600))
	return path
}

func TestLoadMinimalConfig(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
`, dir))

	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, "https://test.example.com", cfg.Endpoint)
	require.Equal(t, "test.example.com", cfg.Domain)
	require.Equal(t, "test.example.com", cfg.Name)
}

func TestLoadFullConfig(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://registry.example.com"
name: "my-registry"
listen: ":8080"
dataDir: %q
keyPath: "/tmp/ap.key"
logLevel: debug
logFormat: text
`, dir))

	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, "my-registry", cfg.Name)
	require.Equal(t, ":8080", cfg.Listen)
	require.Equal(t, dir, cfg.DataDir)
	require.Equal(t, "debug", cfg.LogLevel)
}

func TestDefaults(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
`, dir))

	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, ":5000", cfg.Listen)
	require.Equal(t, dir, cfg.DataDir)
	require.Equal(t, "info", cfg.LogLevel)
	require.Equal(t, "json", cfg.LogFormat)
	require.NotEmpty(t, cfg.RegistryToken, "token should be auto-generated")
}

func TestMissingEndpoint(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
name: "test"
dataDir: %q
`, dir))
	_, err := Load(path)
	require.Error(t, err, "expected error for missing endpoint")
}

func TestInvalidLogLevel(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
logLevel: verbose
`, dir))
	_, err := Load(path)
	require.Error(t, err, "expected error for invalid log level")
}

func TestFileNotFound(t *testing.T) {
	_, err := Load("/nonexistent/path/apoci.yaml")
	require.Error(t, err, "expected error for missing file")
}

func TestBackendsDefaults(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)

	for _, name := range []string{"npm", "cargo", "pypi"} {
		var b BackendConfig
		switch name {
		case "npm":
			b = cfg.Backends.NPM
		case "cargo":
			b = cfg.Backends.Cargo
		case "pypi":
			b = cfg.Backends.PyPI
		}
		require.True(t, b.IsEnabled(), "%s default-enabled", name)
		require.True(t, b.IsFederated(), "%s default-federated", name)
		require.Equal(t, "the-fallback", b.TokenOr("the-fallback"), "%s token falls back", name)
	}
}

func TestBackendsToggles(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
backends:
  npm:
    enabled: false
  cargo:
    federate: false
    token: cargo-only
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)

	require.False(t, cfg.Backends.NPM.IsEnabled())
	require.True(t, cfg.Backends.Cargo.IsEnabled())
	require.False(t, cfg.Backends.Cargo.IsFederated())
	require.Equal(t, "cargo-only", cfg.Backends.Cargo.TokenOr("global"))
	require.Equal(t, "global", cfg.Backends.NPM.TokenOr("global"))
	require.True(t, cfg.Backends.PyPI.IsEnabled(), "unspecified backend stays default-enabled")
}

func TestLimitsDefaults(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, DefaultMaxManifestSize, cfg.Limits.MaxManifestSize)
	require.Equal(t, DefaultMaxBlobSize, cfg.Limits.MaxBlobSize)
}

func TestRegistryTokenAutoGenerated(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
`, dir))

	cfg, err := Load(path)
	require.NoError(t, err)
	require.NotEmpty(t, cfg.RegistryToken, "token should be auto-generated")
	require.Len(t, cfg.RegistryToken, 64, "token should be 32 bytes hex-encoded")

	// Second load should return the same token.
	cfg2, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, cfg.RegistryToken, cfg2.RegistryToken, "token should be stable across loads")
}

func TestRegistryTokenExplicit(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
registryToken: "my-secret-token"
`, dir))

	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, "my-secret-token", cfg.RegistryToken)
}

func TestAccountDomainDefault(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://registry.example.com"
dataDir: %q
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, "registry.example.com", cfg.AccountDomain)
}

func TestAccountDomainExplicit(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://registry.example.com"
dataDir: %q
accountDomain: "example.com"
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, "example.com", cfg.AccountDomain)
	require.Equal(t, "registry.example.com", cfg.Domain)
}

func TestAccountDomainRejectsScheme(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://registry.example.com"
dataDir: %q
accountDomain: "https://example.com"
`, dir))
	_, err := Load(path)
	require.Error(t, err)
	require.Contains(t, err.Error(), "bare hostname")
}

func TestAccountDomainRejectsPort(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://registry.example.com"
dataDir: %q
accountDomain: "example.com:8080"
`, dir))
	_, err := Load(path)
	require.Error(t, err)
	require.Contains(t, err.Error(), "bare hostname")
}

func TestLimitsCustomValues(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
limits:
  maxManifestSize: 5242880
  maxBlobSize: 1073741824
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, int64(5242880), cfg.Limits.MaxManifestSize)
	require.Equal(t, int64(1073741824), cfg.Limits.MaxBlobSize)
}

func TestGCDefaults(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.NotNil(t, cfg.GC.Enabled)
	require.True(t, *cfg.GC.Enabled)
	require.Equal(t, 6*time.Hour, cfg.GC.Interval)
	require.Equal(t, 30*24*time.Hour, cfg.GC.StalePeerBlobAge)
	require.Equal(t, 500, cfg.GC.OrphanBatchSize)
}

func TestGCCustomValues(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
gc:
  enabled: false
  interval: 1h
  stalePeerBlobAge: 168h
  orphanBatchSize: 100
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.NotNil(t, cfg.GC.Enabled)
	require.False(t, *cfg.GC.Enabled)
	require.Equal(t, 1*time.Hour, cfg.GC.Interval)
	require.Equal(t, 168*time.Hour, cfg.GC.StalePeerBlobAge)
	require.Equal(t, 100, cfg.GC.OrphanBatchSize)
}

func TestNotificationsValidEvents(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
notifications:
  events:
    - peer_health
    - gc_error
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, []string{"peer_health", "gc_error"}, cfg.Notifications.Events)
}

func TestNotificationsInvalidEvent(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
notifications:
  events:
    - bogus_event
`, dir))
	_, err := Load(path)
	require.Error(t, err)
	require.Contains(t, err.Error(), "bogus_event")
}

func TestGCNegativeInterval(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
gc:
  interval: -1h
`, dir))
	_, err := Load(path)
	require.Error(t, err)
	require.Contains(t, err.Error(), "gc.interval")
}

func TestFederationDefaults(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, "none", cfg.Federation.AutoAccept)
	require.Equal(t, 7*24*time.Hour, cfg.Federation.OutgoingFollowPendingTTL)
	require.Equal(t, 24*time.Hour, cfg.Federation.OutgoingFollowRejectedTTL)
}

func TestFederationCustomTTLs(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
federation:
  outgoingFollowPendingTTL: 48h
  outgoingFollowRejectedTTL: 12h
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, 48*time.Hour, cfg.Federation.OutgoingFollowPendingTTL)
	require.Equal(t, 12*time.Hour, cfg.Federation.OutgoingFollowRejectedTTL)
}

const tagLatest = "latest"

func TestRetentionPerRepoFromYAML(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
gc:
  retention:
    keepLastN: 5
    perRepo:
      - repo: "foo.com/myapp"
        keepLastN: 10
        maxAge: 168h
        pinnedGlobs: ["latest", "v*"]
      - repo: "foo.com/legacy"
        keepLastN: 1
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.Len(t, cfg.GC.Retention.PerRepo, 2)
	require.Equal(t, "foo.com/myapp", cfg.GC.Retention.PerRepo[0].Repo)
	require.Equal(t, 10, cfg.GC.Retention.PerRepo[0].KeepLastN)
	require.Equal(t, 168*time.Hour, cfg.GC.Retention.PerRepo[0].MaxAge)
	require.Equal(t, []string{tagLatest, "v*"}, cfg.GC.Retention.PerRepo[0].PinnedGlobs)
}

func TestRetentionPerRepoFromEnvJSON(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
`, dir))

	t.Setenv("APOCI_GC_RETENTION_PER_REPO",
		`[{"repo":"foo.com/myapp","keepLastN":10,"maxAge":"168h","pinnedGlobs":["latest"]},{"repo":"foo.com/legacy","keepLastN":1}]`)

	cfg, err := Load(path)
	require.NoError(t, err)
	require.Len(t, cfg.GC.Retention.PerRepo, 2)
	require.Equal(t, "foo.com/myapp", cfg.GC.Retention.PerRepo[0].Repo)
	require.Equal(t, 10, cfg.GC.Retention.PerRepo[0].KeepLastN)
	require.Equal(t, 168*time.Hour, cfg.GC.Retention.PerRepo[0].MaxAge)
	require.Equal(t, []string{tagLatest}, cfg.GC.Retention.PerRepo[0].PinnedGlobs)
	require.Equal(t, "foo.com/legacy", cfg.GC.Retention.PerRepo[1].Repo)
	require.Equal(t, 1, cfg.GC.Retention.PerRepo[1].KeepLastN)
}

func TestRetentionPerRepoDuplicate(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
gc:
  retention:
    perRepo:
      - repo: "foo.com/myapp"
        keepLastN: 10
      - repo: "foo.com/myapp"
        keepLastN: 5
`, dir))
	_, err := Load(path)
	require.Error(t, err)
	require.Contains(t, err.Error(), "duplicate")
}
